# https://gohugo.io/getting-started/configuration/#toml-configuration

# ##################################################
# Hugo-defined variables
baseURL       = "http://example.com/"
title         = "My New Hugo Site"
#languageCode  = "de-ch"
languageCode = "en-us"
theme         = "hugo-theme-w3css-basic"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""


# ##################################################
# Theme-defined configuration

# Enable comments by entering your Disqus shortname
disqusShortname = ""


# ##################################################
# ToDo
[Permalinks]
  blog = "/blog/:year/:month/:day/:filename/"


# ##################################################
[menu]

# Main menu

[[menu.main]]
  weight = 1
  name   = "Home"
  url    = "/"

[[menu.main]]
  weight = 2
  name   = "Contact"
  url    = "/contact/"

[[menu.main]]
  weight = 3
  name   = "Pages"
  url    = "/pages/"

[[menu.main]]
  weight = 4
  name   = "Posts"
  identifier = "posts"

[[menu.main]]
  weight = 1
  name   = "News"
  url    = "/news/"
  parent = "posts"

[[menu.main]]
  weight = 2
  name   = "Blog"
  url    = "/blog/"
  parent = "posts"

[[menu.main]]
  weight = 5
  name   = "FAQ"
  url    = "/faq/"

[[menu.topbar]]
  weight = 1
  name   = "GitHub"
  url    = "https://github.com/it-gro/hugo-theme-w3css-basic"
  pre   = "fa fa-github"

[[menu.topbar]]
  weight = 2
  name   = "Facebook"
  url    = "http://facebook.com"
  pre   = "fa fa-facebook"

[[menu.topbar]]
  weight = 3
  name   = "Twitter"
  url    = "http://twitter.com"
  pre   = "fa fa-twitter"

[[menu.topbar]]
  weight = 4
  name   = "Email"
  url    = "#footer01"
# url    = "mailto:info@example.com"
  pre   = "fa fa-envelope"


# if google translate is not an option, provide multilingual menu
# https://gohugo.io/content-management/multilingual/
#
# [languages.en]
# weight = 0
# languageName = "English"
#  
# [[languages.en.menu.main]]
#   weight = 1
#   name   = "Home"
#   url    = "/"
#  
# [[languages.en.menu.main]]
#   weight = 2
#   name   = "Contact"
#   url    = "/contact/"
#  
# [[languages.en.menu.main]]
#   weight = 3
#   name   = "Pages"
#   url    = "/pages/"
#  
# [[languages.en.menu.main]]
#   weight = 4
#   name   = "Posts"
#   identifier = "posts"
#  
# [[languages.en.menu.main]]
#   weight = 1
#   name   = "News"
#   url    = "/news/"
#   parent = "posts"
#  
# [[languages.en.menu.main]]
#   weight = 2
#   name   = "Blog"
#   url    = "/blog/"
#   parent = "posts"
#  
# [[languages.en.menu.main]]
#   weight = 5
#   name   = "FAQ"
#   url    = "/faq/"
#  
# [languages.de]
# weight = 010
# languageName = "Deutsch"
#  
# [[languages.de.menu.main]]
#   weight = 1
#   name   = "Home"
#   url    = "/"
#  
# [[languages.de.menu.main]]
#   weight = 2
#   name   = "Kontakt"
#   url    = "/contact/"
#  
# [[languages.de.menu.main]]
#   weight = 3
#   name   = "Seiten"
#   url    = "/pages/"
#  
# [[languages.de.menu.main]]
#   weight = 4
#   name   = "Posts"
#   identifier = "posts"
#  
# [[languages.de.menu.main]]
#   weight = 1
#   name   = "News"
#   url    = "/news/"
#   parent = "posts"
#  
# [[languages.de.menu.main]]
#   weight = 2
#   name   = "Blog"
#   url    = "/blog/"
#   parent = "posts"
#  
# [[languages.de.menu.main]]
#   weight = 5
#   name   = "FAQ"
#   url    = "/faq/"

# Top bar social links menu

# ToDo:
#  https://gohugo.io/content-management/menus/
#  > if you make use of the multilingual feature, you can define language-independent menus.
#  how?

# [[languages.en.menu.topbar]]
#   weight = 1
#   name   = "GitHub"
#   url    = "https://github.com/it-gro/hugo-theme-w3css-basic"
#   pre   = "fa fa-github"
#  
# [[languages.en.menu.topbar]]
#   weight = 2
#   name   = "Facebook"
#   url    = "http://facebook.com"
#   pre   = "fa fa-facebook"
#  
# [[languages.en.menu.topbar]]
#   weight = 3
#   name   = "Twitter"
#   url    = "http://twitter.com"
#   pre   = "fa fa-twitter"
#  
# [[languages.en.menu.topbar]]
#   weight = 4
#   name   = "Email"
#   url    = "#footer01"
# # url    = "mailto:info@example.com"
#   pre   = "fa fa-envelope"
#  
# [[languages.de.menu.topbar]]
#   weight = 1
#   name   = "GitHub"
#   url    = "https://github.com/it-gro/hugo-theme-w3css-basic"
#   pre   = "fa fa-github"
#  
# [[languages.de.menu.topbar]]
#   weight = 2
#   name   = "Facebook"
#   url    = "http://facebook.com"
#   pre   = "fa fa-facebook"
#  
# [[languages.de.menu.topbar]]
#   weight = 3
#   name   = "Twitter"
#   url    = "http://twitter.com"
#   pre   = "fa fa-twitter"
#  
# [[languages.de.menu.topbar]]
#   weight = 4
#   name   = "Email"
#   url    = "#footer01"
# # url    = "mailto:info@example.com"
#   pre   = "fa fa-envelope"



# ##################################################
# theme-defined params
[params]

  # used in layouts/partials/head.meta.html
  authorName         = "it-gro"
  defaultKeywords    = ["foo", "bar"]
  defaultDescription = "example site created with hugo using theme hugo-theme-w3css-basic"

  # used in layouts/partials/head.stylesheets.html
  # set W3.CSS color theme (choose one)
  #w3cssColorTheme = "/css/w3-theme-custom.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-amber.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-black.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-blue-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-brown.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-cyan.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-dark-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-deep-orange.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-deep-purple.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-green.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-grey.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-indigo.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-khaki.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-light-blue.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-light-green.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-lime.css"
  w3cssColorTheme = "/vendor/w3css/4/w3-theme-orange.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-pink.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-purple.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-red.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-teal.css"
  #w3cssColorTheme = "/vendor/w3css/4/w3-theme-yellow.css"


  # Google Maps API key
  # get our own: https://developers.google.com/maps/documentation/javascript/adding-a-google-map#key
  # used in layouts/partials/contact.map.html
  # if empty => fallback to URL (instead of map) 
  googleMapsApiKey = ""
  googleMapsZoom   = 14
  latitude         = 46.946692
  longitude        =  7.444186


  # multiple lines in toml
  # https://github.com/toml-lang/toml#user-content-string

  # used in layouts/partials/footer.html
  # uses markdownify
  aboutUs   = '''
Vel illum **dolore** eu 

  * feugiat nulla 
  * facilisis at vero.
              '''
               
  address   = '''
**nobis eleifend**  
**Soluta nobis eleifend**  
illum dolore eu feugiat  
3612 Steffisburg  
consectetuer adipiscing  

**Switzerland**
              '''

  bottomLeft  = "Copyright (c) 2017, *lobortis nisl* ut aliquip ex ea commodo consequat"
  bottomRight = 'created with [Hugo](https://gohugo.io) '


  # used in partials/ids/contact.html
  #
  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #
  # Enable the contact form by entering your Formspree.io email
  email     = "info@example.com"
              
  # Format dates with Go's time formatting
  # used in layouts/partials/recent_posts.html
  # still to do ...
  date_format = "January 2, 2006"
  

# ##################################################
# params.

[params.marquee]
  # enable or disable marquee on frontpage
  enable   = true
 #enable   = false
  marquee  = '''
At [info@example.com](mailto:info@example.com) vero eos et **accusam**
et justo duo dolores et ea rebum. Stet clita *kasd gubergren*, no sea
             '''

[params.menuTopBar]
  # enable or disable menu.topbar with social icons (right)
  socialEnable          = true
  googleTranslateEnable = true

[params.jumbotrons]
  # enable or disable jumbotrons on frontpage
  # see some examples in 'exampleSite/data/jumbotron'
  enable   = true
 #enable   = false

[params.photocards]
  # enable or disable photocards on frontpage
  # see some examples in 'exampleSite/data/photocards'
  enable   = true
 #enable   = false

[params.features]
  # enable or disable features on frontpage
  # see some examples in 'exampleSite/data/features'
  enable   = true
 #enable   = false

[params.testimonials]
  # enable or disable testimonials on frontpage
  # see some examples in 'exampleSite/data/testimonials'
  enable   = true
 #enable   = false
  title    = "TESTIMONIALS"
  subtitle = '''
Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos
et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
             '''

[params.seeMore]
  # enable or disable see_more on frontpage
  enable    = true
 #enable    = false
  icon      = "fa fa-file-code-o"
  title     = "DO YOU WANT TO SEE MORE?"
  linkUrl   = "#"
  linkText  = "consectetuer adipiscing"
  subtitle  = '''
Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper
suscipit lobortis nisl ut aliquip ex ea commodo consequat.
              '''

[params.clients]
  # enable or disable clients on frontpage
  # see some examples in 'exampleSite/data/clients'
  enable = true
  #enable = false
  # All clients are defined in their own files. You can find example items
  # at 'exampleSite/data/clients'.
  # For more informtion take a look at the README.
  title = "OUR CLIENTS"
  subtitle = '''
Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse
**molestie consequat**, vel illum dolore eu feugiat nulla facilisis at
vero eros et accumsan et iusto odio dignissim qui blandit praesent
luptatum zzril delenit augue duis dolore te feugait nulla
facilisi. 
             '''

[params.recent_posts]
  enable = true
  #enable = false
  title    = "FROM OUR BLOG"
  subtitle = '''
Pellentesque habitant morbi tristique senectus et netus et malesuada
fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae,
ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam
egestas semper. Aenean ultricies mi vitae est. Mauris placerat
eleifend leo.
             '''

# Enable and disable widgets for the right sidebar
[params.widgets]
  #categories = true
  #tags = true
  #search = true

# ##################################################
[blackfriday]
  #extensions = ["hardLineBreak"]
  # https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
  # http://commonmark.org/
  # http://spec.commonmark.org/0.28/
  
# emacs
# Local variables:      
# tab-width:        2   
# indent-tabs-mode: nil 
# End:                  
